services:

  web-app:
    build:
      context: .
    volumes:
      - ./src:/src
    environment:
      - DB_HOST=database
      - DB_NAME=db
      - DB_USER=user
      - DB_PASS=password
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  database:
    image: postgres:14.6-alpine
    container_name: database
    restart: always
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "user", "-d", "db" ]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  dbdata:
